version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_DB_VENDOR: POSTGRES
      KC_DB_ADDR: postgres
      KC_DB_PORT: 5432
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_TLS_REQUIRED: none
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  # mail:
  #   image: mailhog/mailhog
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
