version: '3'
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - keycloak-network
    depends_on:
      - postgres
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - keycloak-network

networks:
  keycloak-network:

volumes:
  keycloak-data:
  postgres-data:
