version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    ports:
      - "8080:8080"
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_HTTP_ENABLED: true
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_TLS_REQUIRED: none
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  # mail:
  #   image: mailhog/mailhog
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
