spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/kudaGo
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8080

jwt:
  auth:
    converter:
      resource-id: kudaGoWeb
      principle-attribute: preferred_username